---
title: "Wine"
author: "Study Group 13"
date: "24/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Load the relevant libraries
library(tidyverse)
library(lubridate)
library(mice) 
library(VIM)
library(dplyr)
library(Hmisc)
library(janitor)
library(readxl)
library(skimr)
```

## 1 Background

why are we visualizing this dataset? what do we want to get out of it?

## 2 Load & Inspect Data

We would like to inspect the dataset in the following orders:
2.1 missing, empty, and duplicated values;
2.2 data type;
2.3 weird values, errors, and outliers.

```{r load / inspect data, message = FALSE, warning = FALSE}
# 1. Load the data
original_data <- vroom::vroom("winemag-data-130k-v2.csv") %>% 
  clean_names() %>% 
  select(-x1) # Discard an irrelevant column

# Take a look at the raw data
head(original_data)

# Check for missing values
skim(original_data)

describe(original_data) 

# Check for duplicates
get_dupes(original_data)

# Check data types
glimpse(original_data)

# Check for errors and outliers
ggplot(original_data, aes(x = price)) + geom_boxplot()
ggplot(original_data, aes(x = price)) + geom_histogram(binwidth = 20)
ggplot(original_data, aes(x = points)) + geom_boxplot()
```

Through the inspection, we find:

> *Missing, empty, and duplicated values:*



```{r clean data 1, message = FALSE, warning = FALSE}
#List of all wineries with for entries with no country.
data_process_1 <- original_data %>% 
  filter(is.na(country)) %>% 
  summarise(winery) %>% 
  distinct()

#New list of missing wineries with existing countries.
data_process_2 <- inner_join(original_data, data_process_1, by = "winery") %>%
  group_by(winery, country) %>% 
  summarise(country,winery) %>% 
  distinct()

country_list <- original_data %>% 
  summarise(country) %>% 
  distinct()

winery_list <- original_data %>% 
  group_by(winery) %>% 
  summarise(winery) %>% 
  distinct()

data_process_3 <- data_process_2 %>% 
  na.omit()

clean_data_1 <- original_data %>% 
  mutate(country = case_when( 
    winery %in% data_process_3$winery ~ data_process_3$country,
    TRUE~country
  ))

data_process_4 <- left_join(data_process_1, data_process_2, by = "winery") %>%
  group_by(winery, country) %>% 
  summarise(country,winery) %>% 
  distinct()

```

